# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3"

services:
  hub:
    shm_size: 16G
    ipc: host
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: $JUPYTERHUB_VERSION
    restart: always
    image: jupyterhub
    runtime: nvidia
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "./cfgs/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
      - "${HOST_PERSONAL_NETWORK_FOLDER}:${HOST_PERSONAL_NETWORK_FOLDER}" ### needed for pre spawn hook
      - "${HOST_SHARED_NETWORK_FOLDER}:${HOST_SHARED_NETWORK_FOLDER}" ### not really needed
    ports:
      - "443:443"
    links:
      - hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
      # Network paths
      DOCKER_PERSONAL_NETWORK_FOLDER: ${DOCKER_PERSONAL_NETWORK_FOLDER}
      DOCKER_SHARED_NETWORK_FOLDER: ${DOCKER_SHARED_NETWORK_FOLDER}
      HOST_PERSONAL_NETWORK_FOLDER: ${HOST_PERSONAL_NETWORK_FOLDER}
      # HOST_SHARED_NETWORK_FOLDER: ${HOST_SHARED_NETWORK_FOLDER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JUPYTER_ENABLE_LAB: 1
      GRANT_SUDO: yes
    env_file: ### env files containing variables you do not want to track in GitHub
      - secrets/postgres.env
      - .env
    command: 
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  ngrok:
    image: shkoliar/ngrok:latest
    container_name: jupyterhub-ngrok
    depends_on:
      - hub
    restart: always
    ports:
      - 4551:4551
    links:
    - hub
    environment:
      - DOMAIN=hub
      - PORT=443
      - AUTH_TOKEN=${NGROK_AUTHTOKEN}
      - DEBUG=True
      - REGION=ap

  nginx:
      image: nginx:latest
      container_name: jupyterhub-nginx
      volumes:
        - "./cfgs/nginx.conf:/etc/nginx/nginx.conf:ro"
      ports:
        - 8000:8000
      links:
        - hub

networks:
  default:
    driver: bridge
    name: ${DOCKER_NETWORK_NAME}

volumes:
  data:
    name: ${DATA_VOLUME_HOST}
  db:
    name: ${DB_VOLUME_HOST}
